# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolers', '0003_auto_20161019_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooler',
            name='processed_file',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cooler',
            name='rawfile_in_db',
            field=models.BooleanField(default=False),
        ),
    ]
