name: higlass-server
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python>=3.7
  - numba
  - Pillow
  - pip
  - pip:
    - pybbi==0.2.0
    - bumpversion==0.5.3
    - CacheControl==0.12.4
    - cooler==0.8.6
    - django-cors-headers==3.0.2
    - django-guardian==1.5.1
    - django-rest-swagger==2.2.0
    - django==2.1.5
    - djangorestframework==3.7.3
    - h5py==2.6.0
    - numpy
    - pandas==0.23.4
    - pybase64==0.2.1
    - pyBigWig==0.3.2
    - redis==2.10.5
    - requests==2.20.0
    - scikit-learn
    - slugid==1.0.7
    - bumpversion==0.5.3
    - redis==2.10.5
    - clodius==0.11.2
    - simple-httpfs>=0.1.3
    - pyppeteer>=0.0.25
