# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-19 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizes',
            name='coords',
            field=models.CharField(default='hg19', max_length=8),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='datafile',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
