# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coolers', '0006_auto_20161108_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooler',
            name='twod',
        ),
        migrations.AddField(
            model_name='cooler',
            name='file_type',
            field=models.TextField(default='multires.cool'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cooler',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
