# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import slugid.slugid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChromInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(default=slugid.slugid.nice, max_length=100, unique=True)),
                ('datafile', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ChromSizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(default=slugid.slugid.nice, max_length=100, unique=True)),
                ('datafile', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
