# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fragments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChromInfo',
        ),
        migrations.DeleteModel(
            name='ChromSizes',
        ),
    ]
