# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 04:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import slugid.slugid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tileset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(default=slugid.slugid.nice, max_length=100, unique=True)),
                ('datafile', models.FileField(upload_to='uploads')),
                ('filetype', models.TextField()),
                ('datatype', models.TextField(default='unknown')),
                ('coordSystem', models.TextField()),
                ('coordSystem2', models.TextField(default='')),
                ('private', models.BooleanField(default=False)),
                ('name', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tilesets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
                'permissions': (('view_tileset', 'View tileset'),),
            },
        ),
        migrations.CreateModel(
            name='ViewConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(default=slugid.slugid.nice, max_length=100, unique=True)),
                ('viewconf', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
