# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-31 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilesets', '0002_auto_20170223_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewconf',
            name='higlassVersion',
            field=models.CharField(default='', max_length=5),
        ),
    ]
