# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 16:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tilesets', '0002_auto_20161018_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='tileset',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tileset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tilesets', to=settings.AUTH_USER_MODEL),
        ),
    ]
