# Generated by Django 2.0 on 2018-11-12 03:15

from django.db import migrations, models
import tilesets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tilesets', '0003_viewconf_higlassversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tileset',
            name='group',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tileset',
            name='uuid',
            field=models.CharField(default=tilesets.models.create_uuid, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='viewconf',
            name='higlassVersion',
            field=models.CharField(default='', max_length=16),
        ),
    ]
