# Generated by Django 2.0 on 2018-11-17 20:53

from django.db import migrations, models
import tilesets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tilesets', '0004_auto_20181115_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tileset',
            name='uuid',
            field=models.CharField(default=tilesets.models.generate_slug, max_length=100, unique=True),
        ),
    ]
