# Generated by Django 2.0.9 on 2018-11-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilesets', '0005_auto_20181127_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='tileset',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
