# Generated by Django 2.0.9 on 2018-11-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilesets', '0006_tileset_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
