# Generated by Django 2.0.9 on 2018-11-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tilesets', '0007_auto_20181127_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tileset',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
