# Generated by Django 2.1.5 on 2019-09-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilesets', '0011_auto_20181228_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='tileset',
            name='indexfile',
            field=models.FileField(default=None, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='tileset',
            name='coordSystem2',
            field=models.TextField(blank=True, default=''),
        ),
    ]
