# Generated by Django 3.1 on 2021-11-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilesets', '0012_auto_20190923_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tileset',
            name='indexfile',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads'),
        ),
    ]
